{
 "title": "2. Ecommerce - Microservice Drilldown",
 "tags": [
  "ecommerce",
  "drilldown",
  "microservice"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "cart-service,order-service,payment-service,product-service,user-service,api-gateway"
   }
  ]
 },
 "panels": [
  { "title": "$service Health Profile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "avg(ecommerce_service_cpu_usage_ratio{service=~\"$service\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(ecommerce_service_memory_usage_bytes{service=~\"$service\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "$service Live Log Stream",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"docker\"} |= \"$service\""
    }
   ]
  }
 ]
}