apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: user-service
  namespace: ecommerce
spec:
  replicas: 5
  strategy:
    canary:
      steps:
        - setWeight: 5
        - pause:
            duration: 1m
        - setWeight: 20
        - analysis:
            templates:
              - templateName: success-rate-slo
        - setWeight: 50
        - pause:
            duration: 2m
        - setWeight: 100
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ecommerce-user-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: OTEL_SERVICE_NAME
              value: "user-service"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: MONGO_USERS_URI
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-slo
  namespace: ecommerce
spec:
  args:
    - name: service-name
      value: user-service
  metrics:
    - name: success-rate
      interval: 10s
      successCondition: result[0] >= 0.99
      failureLimit: 3
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
          query: |
            sum(rate(ecommerce_http_requests_total{service="{{args.service-name}}", status_code=~"2..|3.."}[1m]))
            /
            clamp_min(sum(rate(ecommerce_http_requests_total{service="{{args.service-name}}"}[1m])), 0.001)
