apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: ecommerce-payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3005
          env:
            - name: PORT
              value: "3005"
            - name: OTEL_SERVICE_NAME
              value: "payment-service"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: MONGO_PAYMENTS_URI
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ecommerce
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
